// Ancrage juridique par cas — version 16.2.0
export const LEGAL_BASIS = {
 Q:{skill:'x',refs:[]},
  S1:{skill:'Rattacher une facture à la bonne période selon le mode de décompte autorisé.',refs:[{citation:'art. 39, al. 1–2, LTVA',sourceId:'ltva',note:'Le mode convenues est la règle; le mode reçues est soumis à autorisation.'},{citation:'art. 40, al. 1–2, LTVA',sourceId:'ltva',note:'La naissance de la créance dépend du mode de décompte.'}]},
  S2:{skill:'Identifier la naissance de la créance fiscale lors d’un paiement anticipé.',refs:[{citation:'art. 40, al. 1, let. c, LTVA',sourceId:'ltva',note:'Les paiements anticipés sont traités au moment prévu par la loi.'}]},
  S3:{skill:'Traiter une correction documentée de la contre-prestation dans la bonne période.',refs:[{citation:'art. 41, al. 1, LTVA',sourceId:'ltva',note:'La modification de la contre-prestation entraîne une adaptation de la dette fiscale.'},{citation:'décompte AFC — ch. 235',sourceId:'prototype',note:'La diminution de contre-prestation est reportée dans la rubrique prévue.'}]},
  S4:{skill:'Réconcilier les comptes avec ch. 200, les déductions, ch. 299 et les bases TDFN.',refs:[{citation:'art. 37, al. 2–3, LTVA',sourceId:'ltva',note:'La dette TDFN est calculée sur les contre-prestations TVA comprise.'},{citation:'décompte AFC — ch. 200 à 379',sourceId:'prototype',note:'La structure du formulaire permet la concordance entre chiffre d’affaires et calcul TDFN.'}]},
  S5:{skill:'Suivre correctement la périodicité, la remise, le paiement et l’intérêt moratoire.',refs:[{citation:'art. 35, al. 1, LTVA',sourceId:'ltva',note:'Les TDFN sont décomptés semestriellement.'},{citation:'art. 71, al. 1, LTVA',sourceId:'ltva',note:'Le décompte doit être remis dans les 60 jours.'},{citation:'art. 86, al. 1 et art. 87, al. 1, LTVA',sourceId:'ltva',note:'La créance doit être payée dans les 60 jours; un retard peut générer un intérêt moratoire.'}]},
  T1:{skill:'Qualifier un dossier complet avant de construire le décompte.',refs:[{citation:'art. 23, 37 et 45 LTVA',sourceId:'ltva',note:'Exportations, TDFN et acquisitions répondent à des mécanismes distincts.'},{citation:'art. 84, 88 et 91 OTVA',sourceId:'otva',note:'Plusieurs activités TDFN et impôt sur les acquisitions doivent être ventilés selon les règles applicables.'},{citation:'ordonnance AFC sur la valeur des TDFN',sourceId:'rates',note:'Les TDFN du profil doivent correspondre aux activités réelles.'}]},
  T2:{skill:'Établir puis réconcilier un décompte TDFN complet depuis les pièces comptables.',refs:[{citation:'art. 37, al. 2–3, LTVA',sourceId:'ltva',note:'Calcul de la dette selon les TDFN.'},{citation:'art. 45 LTVA',sourceId:'ltva',note:'L’impôt sur les acquisitions est traité séparément de la dette TDFN.'},{citation:'art. 91 OTVA',sourceId:'otva',note:'L’ordonnance précise le traitement des acquisitions sous TDFN.'},{citation:'décompte AFC — ch. 200 à 399 et 900',sourceId:'prototype',note:'Les rubriques du formulaire doivent rester concordantes.'}]}
};
